version: '3.7'

services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:${REDIS_PORT}"
    volumes:
      - redis_data:/data

  db:
    image: postgres:latest
    container_name: db-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  celery:
    build: .
    container_name: celery
    entrypoint: sh -c "celery -A celery_app.celery_app worker -l info"
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  redis_data:
  postgres-data:
