version: '3.7'

services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:${REDIS_PORT}"
    volumes:
      - redis_data:/data

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres-data:
